# DeleteAllTriples.rq
# !! Careful you must be, young Jedi !!
# ---- This script deletes ALL TRIPLES in your graph -----
# Are you sure this is really what you want to do?  
DELETE{
  ?s ?p ?o
}
WHERE{
  ?s ?p ?o
}