###############################################################################
# FILE : /CTDasRDF/SPARQL/graphMetadata.rq
# DESCR: Metadata from CDISCPILOT01.TTl, uploaded to Virtuoso graph CTDasRDF-R
#        Determine when the data was last created. 
# ENDP : Local Virtuoso
# GRAPH: http://localhost:8890/CTDasRDF-R
# OUT  : N/A
# NOTES: Copy-paste into Virtusos SPARQL or into other APIs.
#        Keep LIMIT statement, adjust value as needed.
# TODO : 
###############################################################################

PREFIX cdiscpilot01: <https://raw.githubusercontent.com/phuse-org/CTDasRDF/master/data/rdf/cdiscpilot01.ttl#>
SELECT *
FROM <http://localhost:8890/CTDasRDF-R>
WHERE{
cdiscpilot01:sdtm-graph ?p ?o
} LIMIT 100