###############################################################################
# FILE: CTDasRDF/SPARQL/MiscQueries.rq
# DESC: A collection of miscellaneous SPARQL queries for data uploaded to 
#       Virtuoso. Used as examples/sources for query development.
# REQ : 
# SRC : 
# IN  : 
# OUT : 
# NOTE: 
# TODO: 
###############################################################################

//-----------------------------------------------------------------------------
// Misc Query/Query Templates
//-----------------------------------------------------------------------------

// Number of triples in the CTDasRDF graph
SELECT (COUNT(*) as ?count)
FROM <http://localhost:8890/CTDasRDF>
WHERE {
   ?s ?p ?o .
}

//-- Classes used?
PREFIX rdf: <http://www.w3.org/1999/02/22rdfsyntaxns#>
SELECT DISTINCT ?t 
WHERE {
    ?s rdf:type ?t
}

//-- Properties Used and How often?
SELECT ?p (COUNT(?p) AS ?count) 
WHERE {
    ?s ?p ?o
}
GROUP BY ?p
ORDER BY DESC(?count)

//--Classes used and how often
PREFIX rdf: <http://www.w3.org/1999/02/22rdfsyntaxns#>
SELECT ?t (COUNT(?t) AS ?count) 
WHERE {
    ?s rdf:type ?t
}
GROUP BY ?t


//-- Classes: List a few example instances of a particular class
PREFIX rdf: <http://www.w3.org/1999/02/22rdfsyntaxns#>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
SELECT ?s WHERE {
?s rdf:type foo:bar
}
LIMIT 10



SELECT *
FROM <http://localhost:8890/CTDasRDF>
WHERE {
?s ?p ?o
} LIMIT 10

//-----------------------------------------------------------------------------
//-- Data troubleshooting/checking section
// Subjects that point to the study:hasDate object.
PREFIX study: <https://github.com/phuse-org/CTDasRDF/blob/master/data/rdf/study#>
SELECT ?s ?p ?o
FROM <http://localhost:8890/CTDasRDF>
WHERE {
?s ?p study:hasDate
BIND("study:hasDate" AS ?o)
}


// Counts of Subject triples in each namespace
SELECT count(?study) AS ?Study 
       count(?protocol) AS ?Protocol
       count(?custom) AS ?custom

FROM <http://localhost:8890/CTDasRDF>
WHERE {
  {

    ?protocol ?p ?o
    {FILTER(regex(str(?protocol), "(protocol.ttl#)")) } 
  }
  UNION
  {
    ?study ?p ?o
    {FILTER(regex(str(?study), "(study.ttl)")) } 
  }
  UNION
  {
    ?custom ?p ?o
    {FILTER(regex(str(?study), "(custom#)")) } 
  }

}
# SELECT COUNT(*) as ?count
SELECT *
FROM <http://localhost:8890/CTDasRDF>
WHERE {
?s ?p ?o
# FILTER(regex(str(?s), "(code|custom)#"))
FILTER(regex(str(?s), "(ActivityDate)"))
} LIMIT 500

// Connections between namespaces: code#, study#, time#, cd01p#
SELECT *
FROM <http://localhost:8890/CTDasRDF>
WHERE {
   ?s ?p ?o
   FILTER(regex(str(?s), "(code|study|time|cd01p)#"))
   FILTER(regex(str(?o), "(code|study|time|cd01p)#"))
} LIMIT 50 




