###############################################################################
# FILE: MiscQueries.rq
# DESC: A collection of miscellaneous SPARQL queries for data uploaded to 
#       Virtuoso. Used as examples/sources for query development.
# REQ : 
# SRC : 
# IN  : 
# OUT : 
# NOTE: 
# TODO: 
###############################################################################

//-----------------------------------------------------------------------------
// Misc Query/Query Templates
//-----------------------------------------------------------------------------

// Number of triples in the current graph
SELECT (COUNT(*) as ?count)
WHERE {
   ?s ?p ?o .
}


//-- Properties Used and How often?
SELECT ?p (COUNT(?p) AS ?count) 
WHERE {
    ?s ?p ?o
}
GROUP BY ?p
ORDER BY DESC(?count)


//-- Classes in the graph?
SELECT DISTINCT ?t 
WHERE {
    ?s rdf:type ?t
}

//--Classes used and how often
SELECT ?t (COUNT(?t) AS ?count) 
WHERE {
    ?s rdf:type ?t
} GROUP BY ?t

//-- Classes: List a few example instances of a particular class
//   Change foo:bar to the class of interest. Add prefix as needed.
SELECT ?s WHERE {
?s rdf:type foo:bar
} LIMIT 10

//-----------------------------------------------------------------------------
//-- Data troubleshooting/checking section

