###############################################################################
# FILE: PersonQueries-Misc.rq
# DESC: Various queries related to the person node
# REQ : Stardog
# SRC : 
# IN  : 
# OUT : 
# NOTE: 
# TODO: 
###############################################################################

//-- Triples directly attached to a specified Person node
PREFIX cdiscpilot01: <https://w3id.org/phuse/cdiscpilot01#>
SELECT ?person ?p ?o
WHERE
{
    cdiscpilot01:Person_01-701-1015 ?p ?o .
    BIND("cdiscpilot01:Person_01-701-1015" AS ?person)
} ORDER BY ?p ?o

//-- Paths from person node
PREFIX cdiscpilot01: <https://w3id.org/phuse/cdiscpilot01#>
PATHS 
START ?x = cdiscpilot01:Person_01-701-1015 END ?y 
VIA ?p 
