###############################################################################
# FILE: triplesDownFromSubject.rq
# DESC: All triples down from a named subject, follwing all paths
# REQ : 
# SRC : 
# IN  : Graph: CTDasRDF
# OUT : Construct triples for export
# NOTE: 
# TODO: 
###############################################################################

PREFIX cd01p: <https://raw.githubusercontent.com/phuse-org/CTDasRDF/master/data/rdf/cdiscpilot01-protocol.ttl#> 
PREFIX cdiscpilot01: <https://raw.githubusercontent.com/phuse-org/CTDasRDF/master/data/rdf/cdiscpilot01.ttl#> 
PREFIX code: <https://raw.githubusercontent.com/phuse-org/CTDasRDF/master/data/rdf/code.ttl#> 
PREFIX custom: <https://raw.githubusercontent.com/phuse-org/CTDasRDF/master/data/rdf/custom#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX sdtmterm: <http://rdf.cdisc.org/sdtmterm#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX sp: <http://spinrdf.org/sp#> 
PREFIX spin: <http://spinrdf.org/spin#> 
PREFIX study: <https://raw.githubusercontent.com/phuse-org/CTDasRDF/master/data/rdf/study.ttl#> 
PREFIX time: <http://www.w3.org/2006/time#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 

PREFIX x: <example.org/foo/>

CONSTRUCT { ?s ?p ?o }

WHERE { cdiscpilot01:VisitScreening1_01-701-1015  (x:foo|!x:bar)* ?s . 
        ?s ?p ?o . 
}
