---
title: "Explanation"
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
**Clinical Trials Data as RDF** was initiated at the annual Computational Sciences Symposium conference in Silver Spring Maryland in March, 2017 to investigate the ability of Linked Data to address the challenges inherent in the current standards. SDTM was chosen as the starting point because it is one of the most mature and widely adopted of the CDISC models. SDTM data to support the project was immediately available thanks to the previous efforts of the PhUSE Scripts project [https://github.com/phuse-org/phuse-scripts/tree/master/data/sdtm/cdiscpilot01](https://github.com/phuse-org/phuse-scripts/tree/master/data/sdtm/cdiscpilot01).


## Project White Paper
The white paper provides high level overview of the project goals, philosophy, and deliverables. 

Status: Available for public review at: [https://www.phuse.eu/cs-deliverables-under-review](https://www.phuse.eu/cs-deliverables-under-review), November 2018

## Related PhUSE Publications

* **Transforming Clinical Trials with Linked Data.** USConnect18 (Williams, Oliva). [Paper](http://phusewiki.org/docs/2018_US%20Connect18/TT%20STREAM%202/tt17%20final%20.pdf), [Presentation](http://phusewiki.org/docs/2018_US%20Connect18/TT%20STREAM%202/tt17%20pres.pdf)


[Back to TOC](TableOfContents.md)
